name: Deploy
on:
  pull_request:
    types: [closed]
    branches: [master]
jobs:
  deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - name: weed
        id: weed01
        uses: wowyman/test-circleCI@master
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
